name: Deploy to Project Zakoota Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # use 20 LTS (not 18) for new project

      - name: Setup SSH Key
        run: | 
          mkdir -p ~/.ssh 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Files to Server
        run: |
          rsync -avz \
            --exclude='node_modules' \
            --exclude='.git' \
            -e "ssh -i ~/.ssh/id_rsa" ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/project-zakoota-backend

      - name: Deploy to Server
        run: | 
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/project-zakoota-backend
          git pull origin main || true   # optional if repo already exists
          npm install --production
          pm2 restart project-zakoota-backend || pm2 start src/server.js --name "project-zakoota-backend"
          pm2 save
          EOF
